Repository eclipse/microprofile-starter, pull requests merged in 2019-03, with the labels that each got.

#111 Contributing page
  CONTRIBUTING.md
Labels: task

#110 Process to add new implementations. fixes #61.
  README.md
Labels: task

#113 Adds CircleCI CD/CI pipeline
  .circleci/config.yml
Labels: task

#109 Integrated KumuluzEE v3.2
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/MicroprofileServersAddon.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/SupportedServer.java
  src/main/resources/pom-servers.xml
Labels: Update Supported Implementions, enhancement

#117 Upgrade to PrimeFaces 7.0. Fixes #94.
  pom.xml
  src/main/webapp/resources/css/starter-0.9.css
Labels: enhancement

#116 Default beans.xml generation to mode All. Fixes #90
  src/main/java/org/eclipse/microprofile/starter/DataBean.java
  src/main/java/org/eclipse/microprofile/starter/view/EngineData.java
  src/main/webapp/index.xhtml
Labels: enhancement

#95 Support for Helidon Fixes #4.
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  how-to.md
  pom.xml
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/MicroprofileServersAddon.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/MicroprofileSpec.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/SupportedServer.java
  src/main/java/org/eclipse/microprofile/starter/core/artifacts/CDICreator.java
  src/main/java/org/eclipse/microprofile/starter/core/files/JessieFileTemplateResolver.java
  src/main/java/org/eclipse/microprofile/starter/core/model/BeansXMLMode.java
  src/main/java/org/eclipse/microprofile/starter/core/model/JessieModelInitializer.java
  src/main/java/org/eclipse/microprofile/starter/core/model/JessieSpecification.java
  src/main/java/org/eclipse/microprofile/starter/core/model/MicroProfileVersion.java
  src/main/java/org/eclipse/microprofile/starter/core/model/deserializer/OptionsDeserializer.java
  src/main/java/org/eclipse/microprofile/starter/core/model/serializer/OptionValueSerializer.java
  src/main/java/org/eclipse/microprofile/starter/exception/CustomExceptionHandler.java
  src/main/java/org/eclipse/microprofile/starter/exception/CustomExceptionHandlerFactory.java
  src/main/java/org/eclipse/microprofile/starter/log/DynamoDBLogger.java
  src/main/java/org/eclipse/microprofile/starter/spi/AbstractAddon.java
  src/main/java/org/eclipse/microprofile/starter/view/GeneratorDataBean.java
  src/main/resources/files.lst
  src/main/resources/files/helidon/ProtectedController.java.tpl
  src/main/resources/files/helidon/RestApplication.java.tpl
  src/main/resources/files/helidon/application.yaml.tpl
  src/main/resources/files/helidon/logging.properties.tpl
  src/main/resources/files/helidon/microprofile-config.properties.tpl
  src/main/resources/pom-servers.xml
  src/main/webapp/WEB-INF/faces-config.xml
  src/main/webapp/index.xhtml
Labels: Update Supported Implementions

#127 Add MP version 2.2.
  src/main/java/org/eclipse/microprofile/starter/DataBean.java
  src/main/java/org/eclipse/microprofile/starter/core/model/MicroProfileVersion.java
Labels: enhancement
