Repository eclipse/microprofile-starter, pull requests merged in 2019-02, with the labels that each got.

#60 Remove moduleStructure property and unused files. Fixes #55
  src/main/java/org/eclipse/microprofile/starter/core/artifacts/MavenCreator.java
  src/main/java/org/eclipse/microprofile/starter/core/model/JessieSpecification.java
  src/main/java/org/eclipse/microprofile/starter/core/model/ModuleStructure.java
  src/main/java/org/eclipse/microprofile/starter/core/model/SupportedServer.java
  src/main/java/org/eclipse/microprofile/starter/core/model/deserializer/ModuleDeserializer.java
  src/main/java/org/eclipse/microprofile/starter/core/templates/TemplateModelValues.java
  src/main/java/org/eclipse/microprofile/starter/view/GeneratorDataBean.java
  src/main/resources/templates/default.yaml
  src/main/resources/templates/defaultMP.yaml
  src/main/resources/templates/minimal.yaml
  src/main/resources/templates/octopusprime.yaml
  src/main/resources/templates/opinionated.yaml
  src/main/resources/templates/templates.yaml
Labels: task

#73 Adds Microprofile favicon
  src/main/webapp/index.xhtml
  src/main/webapp/resources/img/mp.ico
Labels: enhancement

#82 Add feedback URL to link. fixes #74
  src/main/webapp/index.xhtml
Labels: bug
