Repository eclipse/microprofile-starter, pull requests merged in 2019-06, with the labels that each got.

#160 Add Payara Micro as MP 2.2. Fixes #159
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/SupportedServer.java
Labels: PR Available, Update Supported Implementions

#156 REST API as documented on https://app.swaggerhub.com/apis/microprofile/starter/1
  Container/start.sh
  README.md
  pom.xml
  src/main/java/org/eclipse/microprofile/starter/Version.java
  src/main/java/org/eclipse/microprofile/starter/core/validation/PackageNameValidator.java
  src/main/java/org/eclipse/microprofile/starter/log/DynamoDBLogger.java
  src/main/java/org/eclipse/microprofile/starter/rest/API.java
  src/main/java/org/eclipse/microprofile/starter/rest/APIEndpointLatest.java
  src/main/java/org/eclipse/microprofile/starter/rest/APIEndpointV1.java
  src/main/java/org/eclipse/microprofile/starter/rest/APIService.java
  src/main/java/org/eclipse/microprofile/starter/rest/model/MPOptionsAvailable.java
  src/main/java/org/eclipse/microprofile/starter/rest/model/Project.java
  src/main/java/org/eclipse/microprofile/starter/validation/PackageValidator.java
  src/main/java/org/eclipse/microprofile/starter/view/EngineData.java
  src/main/java/org/eclipse/microprofile/starter/view/GeneratorDataBean.java
  src/main/resources/REST-README.md
  src/main/webapp/index.xhtml
  src/test/java/org/eclipse/microprofile/starter/DynamoDBLoggerTest.java
  version.txt.sh
Labels: enhancement

#166 Missing payaraVersion for MP 2.2 in generated project
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/PayaraMicroServer.java
Labels: bug

#168 Adds Gitter notification on build
  .circleci/config.yml
Labels: enhancement
