Repository eclipse/microprofile-starter, pull requests merged in 2020-06, with the labels that each got.

#308 Thorntail 2.7.0 for MP 3.3, WildFly 19.1.0.Final, Quarkus 1.3.4.Final
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/SupportedServer.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/QuarkusServer.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/ThorntailServer.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/WildFlyServer.java
Labels: Update Supported Implementions

#307 Links to Runtime Home pages and Version release pages. fixes #284
  src/main/java/org/eclipse/microprofile/starter/DataBean.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/SupportedServer.java
  src/main/webapp/index.xhtml
Labels: enhancement

#314 Wildfly URL, closes issue 313
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/SupportedServer.java
Labels: bug

#316 Closes issue 315, small change in test due to MP33
  src/test/resources/json_examples/v3/supportMatrix_servers.json.segments
Labels: bug
