Repository eclipse/microprofile-starter, pull requests merged in 2020-03, with the labels that each got.

#285 WildFly 19.0.0 for MP 3.2
  src/it/java/org/eclipse/microprofile/starter/TestMatrixTest.java
  src/it/java/org/eclipse/microprofile/starter/utils/Commands.java
  src/it/java/org/eclipse/microprofile/starter/utils/Logs.java
  src/it/java/org/eclipse/microprofile/starter/utils/MPSpec.java
  src/it/java/org/eclipse/microprofile/starter/utils/SpecSelection.java
  src/it/java/org/eclipse/microprofile/starter/utils/Whitelist.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/MicroprofileServersAddon.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/SupportedServer.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/QuarkusServer.java
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/WildFlyServer.java
  src/main/resources/files.lst
  src/main/resources/files/wildfly/microprofile-config.properties.tpl
  src/main/resources/files/wildfly/mp3_x/index.html.tpl
  src/main/resources/files/wildfly/service-b/microprofile-config.properties.tpl
  src/main/resources/pom-servers.xml
Labels: Update Supported Implementions

#274 Circle CI: Adds timeout to maven build, adds TS to dependency:go-offline
  .circleci/config.yml
Labels: bug

#288 Quarkus update to 1.3.0.Final
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/QuarkusServer.java
  src/main/resources/pom-servers.xml
Labels: enhancement

#289 Update Open Liberty Maven plugin version
  src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/LibertyServer.java
Labels: enhancement
